version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s: %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: simple
    stream: ext://sys.stdout
  supervisor_logfile:
    level: NOTSET
    class: logging.FileHandler
    formatter: simple
    filename: logs/supervisor/latest.log
    mode: w
  supervisor_rotatingfile:
    level: NOTSET
    class: logging.handlers.RotatingFileHandler
    backupCount: 7
    formatter: simple
    maxBytes: 5000000
    filename: logs/supervisor/HikLoadSupervisor.log
  worker_logfile:
    level: NOTSET
    class: logging.FileHandler
    formatter: simple
    filename: logs/worker/latest.log
    mode: w
  worker_rotatingfile:
    level: NOTSET
    class: logging.handlers.RotatingFileHandler
    backupCount: 7
    formatter: simple
    maxBytes: 5000000
    filename: logs/worker/HikLoadWorker.log
loggers:
  HikLoadSupervisor:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  HikLoadWorker:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  QueueRuntime:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  HikLoadHandler:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  VideoHandler:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  OnedriveUtils:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  YoutubeUpload:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  EmailSender:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
  hikload:
    level: DEBUG
    handlers: [supervisor_rotatingfile, supervisor_logfile]
    propagate: False
