version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s: %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: NOTSET
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    level: NOTSET
    class: logging.FileHandler
    formatter: simple
    filename: logs/latest.log
    mode: w
  rotatingfile:
    level: NOTSET
    class: logging.handlers.RotatingFileHandler
    backupCount: 7
    formatter: simple
    maxBytes: 5000000
    filename: logs/HikLoad.log
loggers:
  HikLoadHandler:
    level: DEBUG
    handlers: [rotatingfile, logfile]
    propagate: False
  VideoHandler:
    level: DEBUG
    handlers: [rotatingfile, logfile]
    propagate: False
  OnedriveUtils:
    level: DEBUG
    handlers: [rotatingfile, logfile]
    propagate: False
  YoutubeUpload:
    level: DEBUG
    handlers: [rotatingfile, logfile]
    propagate: False
  EmailSender:
    level: DEBUG
    handlers: [rotatingfile, logfile]
    propagate: False
  hikload:
    level: DEBUG
    handlers: [rotatingfile, logfile]
    propagate: False
