name: Package Application

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, arch: x64, name: linux }

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: ${{ matrix.config.arch }}

    - name: Package the app using PyInstaller
      run: |
        pip install -r requirements.txt
        pip install PyInstaller
        pyinstaller hikload.spec

    - uses: actions/upload-artifact@v2
      with:
        name: hikload-${{ matrix.config.name }}-${{ matrix.config.arch }}
        path: dist/hikload